version: "3.2"
services:
  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PACKAGE_NAME: gateway
    volumes:
      - ./apps/gateway/:/app/apps/gateway
    env_file: ./apps/gateway/.env
    environment:
      NATS_HOST: "nats"

  publisher:
    image: andriiuni/events
    platform: linux/arm64
    environment:
      EVENT_ENDPOINT: http://gateway:3000/api/v1/events

  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    command:
      - "-js"
