version: "3.2"
services:
  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PACKAGE_NAME: gateway
    volumes:
      - ./apps/gateway/src/:/app/apps/gateway/src

  publisher:
    image: andriiuni/events   
    environment:
      EVENT_ENDPOINT: http://gateway:3000/api/v1/events

  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    command:
      - "--js"
