services:
  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PACKAGE_NAME: gateway
    volumes:
      - ./apps/gateway/:/app/apps/gateway
    env_file: ./apps/gateway/.env
    environment:
      NATS_HOST: "nats"
    depends_on:
      - nats
      - postgres

  fb-collector:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PACKAGE_NAME: fb-collector
    volumes:
      - ./apps/fb-collector/:/app/apps/fb-collector
    env_file: ./apps/fb-collector/.env
    environment:
      NATS_HOST: "nats"
    depends_on:
      - nats
      - postgres
    command: "sh start.dev.sh"

  ttk-collector:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PACKAGE_NAME: ttk-collector
    volumes:
      - ./apps/ttk-collector/:/app/apps/ttk-collector
    env_file: ./apps/ttk-collector/.env
    environment:
      NATS_HOST: "nats"
    depends_on:
      - nats
      - postgres
    command: "sh start.dev.sh"

  publisher:
    image: andriiuni/events
    platform: linux/arm64
    environment:
      EVENT_ENDPOINT: http://gateway:3000/api/v1/events
    depends_on:
      - gateway

  nats:
    image: nats:latest
    command:
      - "-js"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

# volumes:
#   postgres_data:
